/**
 * seedSpotsSP2.js
 * Adds 40 more curated fishing spots to Firestore `spots` (does NOT clear existing ones)
 */
import { initializeApp } from "firebase/app";
import { getFirestore, doc, setDoc } from "firebase/firestore";
import * as dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: path.join(__dirname, '..', '.env.local') });

const app = initializeApp({
    apiKey: process.env.VITE_FIREBASE_API_KEY,
    authDomain: process.env.VITE_FIREBASE_AUTH_DOMAIN,
    projectId: process.env.VITE_FIREBASE_PROJECT_ID,
    storageBucket: process.env.VITE_FIREBASE_STORAGE_BUCKET,
    messagingSenderId: process.env.VITE_FIREBASE_MESSAGING_SENDER_ID,
    appId: process.env.VITE_FIREBASE_APP_ID,
});
const db = getFirestore(app);

const SPOTS_BATCH2 = [

    // ── PESQUEIROS – Capital e imediações ──────────────────────────────────
    {
        id: "pesqueiro_parque_anhanguera",
        name: "Pesqueiro Parque Anhanguera",
        type: "Pesqueiro",
        lat: -23.4712, lng: -46.7631,
        rating: 4.2, reviewCount: 1840,
        address: "Perus, São Paulo – SP",
        distance: "30 km do centro",
        state: "SP",
        species: ["Tilápia", "Carpa", "Bagre", "Lambari"],
        description: "Pesqueiro dentro do Parque Estadual de Anhanguera. Lago grande, bem manejado, infraestrutura familiar completa.",
        dicas: "Milho e minhoca funcionam o ano todo. Chegue cedo — fila nos fins de semana.",
        regras: "Sem pesca noturna. Devolução de espécies nativas obrigatória.",
        preco: "R$ 55–85/dia",
        googleMapsUrl: "https://maps.google.com/?q=-23.4712,-46.7631"
    },
    {
        id: "pesqueiro_campo_limpo",
        name: "Pesqueiro Vale Verde",
        type: "Pesqueiro",
        lat: -23.6431, lng: -46.7892,
        rating: 4.3, reviewCount: 967,
        address: "Campo Limpo Paulista, SP",
        distance: "55 km da capital",
        state: "SP",
        species: ["Tilápia", "Pacu", "Tucunaré", "Carpa"],
        description: "Pesqueiro bem avaliado em Campo Limpo Paulista. Lagos limpos, boa sombra e estrutura de restaurante.",
        dicas: "Pacu responde bem ao caramujo esmagado. Tucunaré bate de manhã no plug.",
        regras: "Pesca com vara e anzol apenas. Proibido tarrafa.",
        preco: "R$ 70–100/dia",
        googleMapsUrl: "https://maps.google.com/?q=-23.6431,-46.7892"
    },
    {
        id: "pesqueiro_cajamar",
        name: "Pesqueiro Rio das Pedras",
        type: "Pesqueiro",
        lat: -23.3571, lng: -46.8763,
        rating: 4.1, reviewCount: 543,
        address: "Cajamar, SP",
        distance: "40 km da capital",
        state: "SP",
        species: ["Tilápia", "Lambari", "Bagre", "Curimba"],
        description: "Pequeno pesqueiro familiar às margens do Rio das Pedras em Cajamar. Tran quilo e bem estruturado.",
        dicas: "Minhoca no fundo pega bagre grande. Tilápia na superfície com pão.",
        regras: "Crianças até 12 anos não pagam.",
        preco: "R$ 50/dia (por kg capturado separado)",
        googleMapsUrl: "https://maps.google.com/?q=-23.3571,-46.8763"
    },
    {
        id: "pesqueiro_santo_andre_2",
        name: "Pesqueiro Aquario Azul",
        type: "Pesqueiro",
        lat: -23.6543, lng: -46.5201,
        rating: 4.0, reviewCount: 412,
        address: "São Bernardo do Campo, SP",
        distance: "28 km da capital",
        state: "SP",
        species: ["Tilápia", "Tucunaré", "Carpa"],
        description: "Pesqueiro urbano em São Bernardo. Ótimo para quem mora no ABC e quer pescar sem sair da região.",
        dicas: "Tucunaré na superfície no lago 2 — use zaras pequenas nas primeiras horas.",
        regras: "Horário: 6h–17h. Peixe devolvido ou pesado para pagamento.",
        preco: "Entrada R$ 30 + R$ 16/kg",
        googleMapsUrl: "https://maps.google.com/?q=-23.6543,-46.5201"
    },
    {
        id: "pesqueiro_embu_guacu",
        name: "Pesqueiro Recanto da Serra",
        type: "Pesqueiro",
        lat: -23.8293, lng: -46.8103,
        rating: 4.4, reviewCount: 756,
        address: "Embu-Guaçu, SP",
        distance: "48 km da capital",
        state: "SP",
        species: ["Tilápia", "Tambaqui", "Pacu", "Bagre"],
        description: "Pesqueiro em área rural com beleza natural da Serra do Mar. Excelente estrutura de lazer e gastronomia.",
        dicas: "Tambaqui e pacu na região mais funda. Use boliche de milho fermentado.",
        regras: "Reserva recomendada para fins de semana.",
        preco: "R$ 80–120/dia com churrasco incluso",
        googleMapsUrl: "https://maps.google.com/?q=-23.8293,-46.8103"
    },
    {
        id: "pesqueiro_osasco",
        name: "Pesqueiro Cidade Nova",
        type: "Pesqueiro",
        lat: -23.5234, lng: -46.8012,
        rating: 3.9, reviewCount: 328,
        address: "Osasco, SP",
        distance: "20 km da capital",
        state: "SP",
        species: ["Tilápia", "Lambari", "Bagre"],
        description: "Pesqueiro dentro da cidade de Osasco — o mais próximo do centro de SP. Ideal para quem tem pouco tempo e quer pescar.",
        dicas: "Fubá e pão funcionam bem. Ótimo para levar crianças na primeira vez.",
        regras: "Horário limitado 7h–17h.",
        preco: "R$ 40/entrada + R$ 14/kg",
        googleMapsUrl: "https://maps.google.com/?q=-23.5234,-46.8012"
    },
    {
        id: "pesqueiro_pilar_sul",
        name: "Pesqueiro Pilar do Sul",
        type: "Pesqueiro",
        lat: -23.8171, lng: -47.7221,
        rating: 4.3, reviewCount: 489,
        address: "Pilar do Sul, SP",
        distance: "130 km da capital",
        state: "SP",
        species: ["Tilápia", "Pacu", "Traíra", "Tucunaré"],
        description: "Pesqueiro de interior em Pilar do Sul. Lago bem conservado e peixes seletos. Área para churrasco.",
        dicas: "Traíra nas margens de manhã com sapo artificial ou minhocão vivo.",
        regras: "Traíra acima de 25cm deve ser devolvida.",
        preco: "R$ 65–95/dia",
        googleMapsUrl: "https://maps.google.com/?q=-23.8171,-47.7221"
    },
    {
        id: "pesqueiro_atibaia",
        name: "Pesqueiro Atibaia Fishing",
        type: "Pesqueiro",
        lat: -23.1172, lng: -46.5503,
        rating: 4.5, reviewCount: 1340,
        address: "Atibaia, SP",
        distance: "70 km da capital",
        state: "SP",
        species: ["Tilápia", "Tucunaré", "Pacu", "Tambaqui", "Carpa"],
        description: "Um dos pesqueiros mais bem estruturados do estado. Vários lagos com target por espécie. Gramado, café e restaurante.",
        dicas: "Carpa no lago especial com boillie. Tucunaré esportivo no lago de iscas artificiais.",
        regras: "Lago de carpa somente com isca artificial (boillie). Devolução obrigatória.",
        preco: "R$ 100–180/dia (varia por lago)",
        googleMapsUrl: "https://maps.google.com/?q=-23.1172,-46.5503"
    },
    {
        id: "pesqueiro_ibiuna",
        name: "Pesqueiro Represa de Ibiúna",
        type: "Pesqueiro",
        lat: -23.6573, lng: -47.2212,
        rating: 4.2, reviewCount: 634,
        address: "Ibiúna, SP",
        distance: "75 km da capital",
        state: "SP",
        species: ["Tucunaré", "Truta-arco-íris", "Tilápia", "Traíra"],
        description: "Pesqueiro diferenciado em Ibiúna com opção de pesca de truta em tanque. Um dos poucos da região de SP com truta.",
        dicas: "Truta morde streamer ou cucharilla. Tucunaré no lago maior com jig shad pequeno.",
        regras: "Truta: precisa comprar a isca especial no local (pellet).",
        preco: "R$ 80/dia. Truta: R$ 45 extra.",
        googleMapsUrl: "https://maps.google.com/?q=-23.6573,-47.2212"
    },
    {
        id: "pesqueiro_sao_jose_campos",
        name: "Pesqueiro Taubaté Fishing",
        type: "Pesqueiro",
        lat: -23.0312, lng: -45.5563,
        rating: 4.4, reviewCount: 892,
        address: "Taubaté, SP",
        distance: "140 km da capital",
        state: "SP",
        species: ["Tilápia", "Pacu", "Tambaqui", "Pintado"],
        description: "Pesqueiro premium do Vale do Paraíba. Pintado em lago especial com serviço de guia. Estrutura de resort.",
        dicas: "Pintado ativo de madrugada. Reserve e pague antecipado para garantir vaga no lago especial.",
        regras: "Lago do pintado: equipamento acima de 30lb obrigatório.",
        preco: "R$ 90–200/dia (varia por lago)",
        googleMapsUrl: "https://maps.google.com/?q=-23.0312,-45.5563"
    },

    // ── PESQUEIROS – Interior Paulista ────────────────────────────────────
    {
        id: "pesqueiro_bauru",
        name: "Pesqueiro Thermas Way Bauru",
        type: "Pesqueiro",
        lat: -22.3341, lng: -49.0823,
        rating: 4.3, reviewCount: 1021,
        address: "Bauru, SP",
        distance: "330 km da capital",
        state: "SP",
        species: ["Tilápia", "Pacu", "Tucunaré", "Surubim"],
        description: "O maior complexo de pesca de Bauru. Vários lagos temáticos, restaurante premium e hotel.",
        dicas: "Surubim disponível em lago pague-por-peso. Reserve com antecedência.",
        regras: "Lago do surubim: guia obrigatório, anzol circular /0 8.",
        preco: "R$ 80–280/dia (por lago)",
        googleMapsUrl: "https://maps.google.com/?q=-22.3341,-49.0823"
    },
    {
        id: "pesqueiro_botucatu",
        name: "Pesqueiro Recanto Botucatu",
        type: "Pesqueiro",
        lat: -22.8803, lng: -48.4443,
        rating: 4.4, reviewCount: 678,
        address: "Botucatu, SP",
        distance: "230 km da capital",
        state: "SP",
        species: ["Tilápia", "Pacu", "Tambaqui", "Traíra"],
        description: "Pesqueiro bem avaliado em Botucatu, famosa pela fauna e clima agradável.",
        dicas: "Traíra nas bordas com vegetação aquática de manhã. Use sapo de silicone.",
        regras: "Proibido pesca com tarrafa e isca viva trazida de fora.",
        preco: "R$ 75–110/dia",
        googleMapsUrl: "https://maps.google.com/?q=-22.8803,-48.4443"
    },
    {
        id: "pesqueiro_marilia",
        name: "Pesqueiro Trilha Verde",
        type: "Pesqueiro",
        lat: -22.2193, lng: -49.9341,
        rating: 4.2, reviewCount: 443,
        address: "Marília, SP",
        distance: "440 km da capital",
        state: "SP",
        species: ["Tilápia", "Pacu", "Tucunaré", "Curimbatá"],
        description: "Pesqueiro da região de Marília com ambiente campestre tranquilo e peixes bem alimentados.",
        dicas: "Matraca de milho na margem da tarde concentra tilápias grandes.",
        regras: "Camping disponível no local com taxa adicional.",
        preco: "R$ 60–90/dia",
        googleMapsUrl: "https://maps.google.com/?q=-22.2193,-49.9341"
    },

    // ── REPRESAS – Complementares ────────────────────────────────────────
    {
        id: "represa_porto_primavera",
        name: "Represa Porto Primavera",
        type: "Represa",
        lat: -22.4932, lng: -52.9781,
        rating: 4.7, reviewCount: 2734,
        address: "Rosana/Presidente Epitácio, SP",
        distance: "640 km da capital",
        state: "SP",
        species: ["Dourado", "Pintado", "Pacu", "Piranha", "Jaú"],
        description: "Uma das melhores represas do Brasil para pesca esportiva. Dourados acima de 10kg são comuns. Ambiente ainda muito preservado.",
        dicas: "Dourado: corrico rápido em canal fundo com colher grande dourada. Pintado: tuvira no poço.",
        regras: "Licença IBAMA. Defeso rigoroso no verão. Guia credenciado recomendado.",
        preco: "Pousadas de pesca R$ 300–600/diária com tudo incluso.",
        googleMapsUrl: "https://maps.google.com/?q=-22.4932,-52.9781"
    },
    {
        id: "represa_ilha_solteira",
        name: "Represa de Ilha Solteira",
        type: "Represa",
        lat: -20.4312, lng: -51.3412,
        rating: 4.6, reviewCount: 1987,
        address: "Ilha Solteira, SP",
        distance: "590 km da capital",
        state: "SP",
        species: ["Dourado", "Pintado", "Pacu", "Tucunaré", "Curvina"],
        description: "Represa do Rio Paraná na fronteira SP/MS. Recordes de dourado são batidos todo ano. Infraestrutura completa.",
        dicas: "Corrico com iscas grandes de 20cm para dourado acima de 8kg. Saída ao amanhecer.",
        regras: "Licença e tamanho mínimo obrigatórios. Catch-and-release fortemente recomendado.",
        preco: "Hotéis de pesca R$ 250–500/dia.",
        googleMapsUrl: "https://maps.google.com/?q=-20.4312,-51.3412"
    },
    {
        id: "represa_jupia",
        name: "Represa de Jupiá",
        type: "Represa",
        lat: -20.7634, lng: -51.6321,
        rating: 4.5, reviewCount: 1456,
        address: "Três Lagoas – MS / Castilho – SP",
        distance: "560 km da capital",
        state: "SP",
        species: ["Dourado", "Pintado", "Curvina", "Jaú", "Pacu"],
        description: "Fronteira SP/MS no Rio Paraná. Famosa pelos dourados recordistas e pintados de 60kg+.",
        dicas: "Pesca de corrico para dourado e isca viva para pintado. Traga guia experiente.",
        regras: "Respeite as regulamentações dos dois estados.",
        preco: "Pousadas R$ 200–400/diária.",
        googleMapsUrl: "https://maps.google.com/?q=-20.7634,-51.6321"
    },
    {
        id: "represa_capivara",
        name: "Represa Capivara — Paranapanema",
        type: "Represa",
        lat: -22.6512, lng: -49.9823,
        rating: 4.4, reviewCount: 1123,
        address: "Porecatu/Piraju, PR/SP",
        distance: "390 km da capital",
        state: "SP",
        species: ["Dourado", "Pintado", "Curvina", "Pacu"],
        description: "Grande represa do Paranapanema na divisa SP/PR. Menos congestionada que Barra Bonita com peixes excelentes.",
        dicas: "Melhor na seca de Maio a Setembro. Dourado nas corredeiras logo abaixo da barragem.",
        regras: "Regulamentação SP e PR — siga a mais restritiva.",
        preco: "Barcos aluguel R$ 100–200/dia.",
        googleMapsUrl: "https://maps.google.com/?q=-22.6512,-49.9823"
    },
    {
        id: "represa_rio_negrinho",
        name: "Lagos da Pedreira — Represa Tietê",
        type: "Represa",
        lat: -22.6892, lng: -48.0712,
        rating: 4.3, reviewCount: 789,
        address: "Dois Córregos, SP",
        distance: "250 km da capital",
        state: "SP",
        species: ["Curvina", "Dourado", "Tucunaré", "Pintado"],
        description: "Trecho do Tietê em Dois Córregos com pesca excelente de curvinas e tucunarés. Menos visitado.",
        dicas: "Jig vertical de 21g para curvina nos poços fundo 10–20m. Marca de peixe no sonar.",
        regras: "Licença estadual obrigatória.",
        preco: "Acesso público + barcos aluguel R$ 80/dia.",
        googleMapsUrl: "https://maps.google.com/?q=-22.6892,-48.0712"
    },
    {
        id: "represa_furnas_sp",
        name: "Reservatório de Furnas — SP/MG",
        type: "Represa",
        lat: -20.6712, lng: -46.3212,
        rating: 4.6, reviewCount: 2341,
        address: "São José da Barra, MG / Fronteira SP",
        distance: "480 km da capital",
        state: "SP",
        species: ["Tucunaré", "Dourado", "Pintado", "Pacu", "Curvina"],
        description: "Gigantesco reservatório no Rio Grande. Um dos melhores do Brasil para tucunaré e dourado. Recordes históricos.",
        dicas: "Tucunaré: plug articulado de 15cm no cedo e tarde. Colônia de peixes nos baixios com sonar.",
        regras: "Licença IBAMA. Regulamentação MG e SP.",
        preco: "Pousadas e barcos R$ 200–500/dia.",
        googleMapsUrl: "https://maps.google.com/?q=-20.6712,-46.3212"
    },
    {
        id: "represa_rio_grande_col",
        name: "Represa Jaguara — Rio Grande",
        type: "Represa",
        lat: -19.9823, lng: -47.4312,
        rating: 4.4, reviewCount: 934,
        address: "Igarapava, SP / Fronteira MG",
        distance: "490 km da capital",
        state: "SP",
        species: ["Dourado", "Pintado", "Curvina", "Pacu"],
        description: "Represa do Rio Grande na divisa SP/MG preservada e com boa população de dourados.",
        dicas: "Dourado nas proximidades da barragem em corrente forte. Colher ou isca grande.",
        regras: "Barco e licença obrigatórios.",
        preco: "Guias locais R$ 180–350/dia.",
        googleMapsUrl: "https://maps.google.com/?q=-19.9823,-47.4312"
    },

    // ── RIOS – Complementares ────────────────────────────────────────────
    {
        id: "rio_turvo",
        name: "Rio Turvo — Santa Fé do Sul",
        type: "Rio",
        lat: -20.2134, lng: -50.9234,
        rating: 4.4, reviewCount: 432,
        address: "Santa Fé do Sul, SP",
        distance: "580 km da capital",
        state: "SP",
        species: ["Dourado", "Pintado", "Pacu", "Piranha"],
        description: "Rio Turvo desemboca no Paraná próximo a Santa Fé. Pouco esforço de pesca, peixes grandes.",
        dicas: "Dourado nas corredeiras logo após a confluência com o Paraná.",
        regras: "Licença IBAMA. Área com mata ciliar preservada — respeite.",
        preco: "Acampamentos R$ 40–80/noite.",
        googleMapsUrl: "https://maps.google.com/?q=-20.2134,-50.9234"
    },
    {
        id: "rio_aguapei",
        name: "Rio Aguapeí — Pacaembu",
        type: "Rio",
        lat: -21.5612, lng: -51.2734,
        rating: 4.2, reviewCount: 287,
        address: "Pacaembu, SP",
        distance: "530 km da capital",
        state: "SP",
        species: ["Dourado", "Curvina", "Bagre", "Pintado"],
        description: "Rio Aguapeí (ou Santo Anastácio) — pouco explorado com bons dourados e ambiente preservado.",
        dicas: "Peixes grandes dado o baixo esforço de pesca. Traga toda a estrutura do acampamento.",
        regras: "Licença. Respeite o período de defeso.",
        preco: "Acesso gratuito em pontos públicos.",
        googleMapsUrl: "https://maps.google.com/?q=-21.5612,-51.2734"
    },
    {
        id: "rio_sapucai",
        name: "Rio Sapucaí-Mirim — Franca",
        type: "Rio",
        lat: -20.5383, lng: -47.4023,
        rating: 4.1, reviewCount: 234,
        address: "Franca, SP",
        distance: "400 km da capital",
        state: "SP",
        species: ["Dourado", "Curimbatá", "Bagre", "Lambari"],
        description: "Tributário do Rio Grande na região de Franca. Dourados menores mas combativos, e curimbatás em grande quantidade.",
        dicas: "Curimbatá nas partes de corredeira com isca de fundo. Dourado no poço abaixo.",
        regras: "Licença estadual. Propriedades privadas nas margens — cuidado com acesso.",
        preco: "Acesso gratuito em pontes estaduais.",
        googleMapsUrl: "https://maps.google.com/?q=-20.5383,-47.4023"
    },
    {
        id: "rio_ribeira",
        name: "Rio Ribeira de Iguape — Eldorado",
        type: "Rio",
        lat: -24.5232, lng: -48.1134,
        rating: 4.5, reviewCount: 891,
        address: "Eldorado, SP",
        distance: "190 km da capital",
        state: "SP",
        species: ["Robalo", "Traíra", "Bagre", "Cará", "Piabanha"],
        description: "Rio de Mata Atlântica com águas cristalinas e diversidade única. Pesca de robalo dentro do rio é a grande atração.",
        dicas: "Robalo sobe o rio na maré cheia. Camarão vivo nos remansos funciona muito bem.",
        regras: "Área de preservação permanente — respeite a APA. Licença.",
        preco: "Acampamentos locais R$ 50–100/noite. Passeios de canoa disponíveis.",
        googleMapsUrl: "https://maps.google.com/?q=-24.5232,-48.1134"
    },
    {
        id: "rio_juquiha",
        name: "Rio Juquiá — Pedro de Toledo",
        type: "Rio",
        lat: -24.2834, lng: -47.2334,
        rating: 4.3, reviewCount: 567,
        address: "Pedro de Toledo, SP",
        distance: "155 km da capital",
        state: "SP",
        species: ["Robalo", "Traíra", "Bagre", "Cará"],
        description: "Rio de Mata Atlântica preservado no litoral sul. Robalo sobe até a cabeceira em baixamar.",
        dicas: "Pesca à noite com lamparina e camarão artesanal. Experiência única.",
        regras: "Área de UCs — licença e guia credenciado recomendados.",
        preco: "Guias locais R$ 150–250/dia.",
        googleMapsUrl: "https://maps.google.com/?q=-24.2834,-47.2334"
    },
    {
        id: "rio_taquari_sp",
        name: "Rio Taquari — Região de Angatuba",
        type: "Rio",
        lat: -23.4912, lng: -48.4023,
        rating: 4.0, reviewCount: 198,
        address: "Angatuba, SP",
        distance: "205 km da capital",
        state: "SP",
        species: ["Traíra", "Bagre", "Lambari", "Cará"],
        description: "Rio de pequeno porte, tranquilo e acessível. Ótimo para quem busca pesca leve e sossego.",
        dicas: "Traíra às margens sombreadas de madrugada com minhocão.",
        regras: "Acesso via propriedades — solicite permissão. Licença estadual.",
        preco: "Gratuito nos pontos de acesso público.",
        googleMapsUrl: "https://maps.google.com/?q=-23.4912,-48.4023"
    },
    {
        id: "rio_tibagi_fronteira",
        name: "Rio Itararé — Fronteira PR",
        type: "Rio",
        lat: -23.8634, lng: -49.3312,
        rating: 4.2, reviewCount: 312,
        address: "Itararé, SP",
        distance: "280 km da capital",
        state: "SP",
        species: ["Dourado", "Curvina", "Curimbatá", "Bagre"],
        description: "Rio Itararé faz divisa SP/PR. Águas limpas, corredeiras e boa população de dourados.",
        dicas: "Dourado nas corredeiras logo abaixo das pontes. Colher espelhada funciona bem.",
        regras: "Licença dos dois estados. Portarias do Parque Estadual do Espigão Alto — respeite.",
        preco: "Camping R$ 30–60/noite.",
        googleMapsUrl: "https://maps.google.com/?q=-23.8634,-49.3312"
    },

    // ── COSTÃO / MARÍTIMO – Complementares ──────────────────────────────
    {
        id: "pesca_caraguatatuba",
        name: "Caraguatatuba — Trapiche e Costão",
        type: "Costão",
        lat: -23.6212, lng: -45.4131,
        rating: 4.2, reviewCount: 734,
        address: "Caraguatatuba, SP",
        distance: "200 km da capital",
        state: "SP",
        species: ["Garoupa", "Vermelho", "Pescada", "Olhete"],
        description: "Bom acesso ao costão rochoso de Caraguatatuba com garoupas e vermelhos. Mar relativamente calmo.",
        dicas: "Lula e sardinha fresca nos fundões de 15–30m para vermelho e garoupa.",
        regras: "Garoupa tem tamanho mínimo 40cm. Não pesque dentro de unidades de conservação.",
        preco: "Barcos de aluguel R$ 200–400/dia.",
        googleMapsUrl: "https://maps.google.com/?q=-23.6212,-45.4131"
    },
    {
        id: "pesca_ilhabela",
        name: "Ilhabela — Pesca Oceânica",
        type: "Costão",
        lat: -23.7812, lng: -45.3523,
        rating: 4.7, reviewCount: 1876,
        address: "Ilhabela, SP",
        distance: "220 km da capital",
        state: "SP",
        species: ["Atum", "Marlim", "Mahi-mahi", "Garoupa", "Barracuda"],
        description: "Um dos melhores destinos de pesca oceânica do sudeste. Corrente do Brasil traz peixes pelágicos de grande porte.",
        dicas: "Mahi-mahi com trolling de iscas coloridas de Nov a Mar. Barracuda nos costões com jig metálico.",
        regras: "Barco com capitão habilitado obrigatório. Marlim: devolução incentivada.",
        preco: "Barcos offshore R$ 800–2000/dia (grupo de até 8).",
        googleMapsUrl: "https://maps.google.com/?q=-23.7812,-45.3523"
    },
    {
        id: "pesca_guaruja",
        name: "Guarujá — Santo Amaro e Costão",
        type: "Costão",
        lat: -23.9934, lng: -46.2562,
        rating: 4.1, reviewCount: 1023,
        address: "Guarujá, SP",
        distance: "80 km da capital",
        state: "SP",
        species: ["Robalo", "Tainha", "Linguado", "Corvina", "Pescada"],
        description: "Canal de Santos e costões do Guarujá são excelentes para robalo e corvina. Acesso fácil da capital.",
        dicas: "Robalo no canal estuarino na virada da maré. Camarão vivo no fundo perto de pilastras.",
        regras: "Respeite as áreas de exclusão de pesca do porto de Santos.",
        preco: "Barcos locais R$ 150–300/dia.",
        googleMapsUrl: "https://maps.google.com/?q=-23.9934,-46.2562"
    },
    {
        id: "pesca_peruibe",
        name: "Peruíbe — Rio Una e Praia",
        type: "Costão",
        lat: -24.3212, lng: -47.0023,
        rating: 4.3, reviewCount: 543,
        address: "Peruíbe, SP",
        distance: "140 km da capital",
        state: "SP",
        species: ["Robalo", "Corvina", "Bagre-marinho", "Parati", "Anchova"],
        description: "Combina pesca estuarina no Rio Una com surf casting na praia aberta. Robalo ao anoitecer no rio.",
        dicas: "Anchova de Março a Maio invadindo a arrebentação com isca de camarão cortado.",
        regras: "Rio Una está dentro do Parque Estadual Juréia-Itatins — respeite as restrições.",
        preco: "Acesso gratuito. Guias locais R$ 150/dia.",
        googleMapsUrl: "https://maps.google.com/?q=-24.3212,-47.0023"
    },
    {
        id: "pesca_iguape",
        name: "Iguape — Mar Pequeno",
        type: "Costão",
        lat: -24.7012, lng: -47.5534,
        rating: 4.5, reviewCount: 1234,
        address: "Iguape, SP",
        distance: "190 km da capital",
        state: "SP",
        species: ["Robalo", "Corvina", "Linguado", "Bagre-amarelo", "Tainha"],
        description: "Mar Pequeno de Iguape é um imenso estuário com peixes em abundância. Um dos segredos mais bem guardados do litoral sul.",
        dicas: "Robalo em toda extensão do Mar Pequeno. Maré enchente de Outubro a Março é imbatível.",
        regras: "APA da Baleia Franca cobre parte da área — guia credenciado recomendado.",
        preco: "Barcos locais R$ 120–250/dia.",
        googleMapsUrl: "https://maps.google.com/?q=-24.7012,-47.5534"
    },
    {
        id: "pesca_praia_grande",
        name: "Praia Grande — Surf Casting",
        type: "Costão",
        lat: -24.0071, lng: -46.4121,
        rating: 3.9, reviewCount: 523,
        address: "Praia Grande, SP",
        distance: "70 km da capital",
        state: "SP",
        species: ["Corvina", "Anchova", "Pescada", "Bagre-amarelo"],
        description: "Praia aberta do litoral sul paulista ideal para surf casting. Corvinas e anchovas são a principal atração da arrebentação.",
        dicas: "Vara de surf 3.5m com chumbo 100g e isca de camarão ou lula. Saída de madrugada.",
        regras: "Pesca somente com vara e anzol. Sem redes.",
        preco: "Acesso gratuito à praia.",
        googleMapsUrl: "https://maps.google.com/?q=-24.0071,-46.4121"
    },

    // ── BÔNUS — Spots históricos e diferenciados ─────────────────────────
    {
        id: "represa_atibainha",
        name: "Sistema Cantareira — Represa Atibainha",
        type: "Represa",
        lat: -23.0712, lng: -46.3823,
        rating: 4.0, reviewCount: 345,
        address: "Nazaré Paulista, SP",
        distance: "80 km da capital",
        state: "SP",
        species: ["Tucunaré", "Tilápia", "Traíra", "Lambari"],
        description: "Uma das represas do sistema Cantareira com acesso ao público em alguns pontos. Tucunarés de bom porte.",
        dicas: "Acesse pela estrada de Nazaré Paulista. Plug articulado de 10cm para tucunaré.",
        regras: "Área de proteção de manancial. Acesso somente nos pontos autorizados pela SABESP.",
        preco: "Acesso gratuito nos pontos públicos.",
        googleMapsUrl: "https://maps.google.com/?q=-23.0712,-46.3823"
    },
    {
        id: "rio_mogi_monteiro",
        name: "Rio Mogi — Mogi das Cruzes",
        type: "Rio",
        lat: -23.5234, lng: -46.1823,
        rating: 4.0, reviewCount: 287,
        address: "Mogi das Cruzes, SP",
        distance: "60 km da capital",
        state: "SP",
        species: ["Traíra", "Lambari", "Bagre", "Cará"],
        description: "Trecho urbano e peri-urbano do Rio Mogi acessível, ótimo para pesca leve e casual próximo à capital.",
        dicas: "Traíra logo ao amanhecer nas margens vegetadas. Minhoca ou camarão.",
        regras: "Licença estadual. O rio passa por área de APA.",
        preco: "Acesso gratuito.",
        googleMapsUrl: "https://maps.google.com/?q=-23.5234,-46.1823"
    },
    {
        id: "pesqueiro_salto_sp",
        name: "Pesqueiro Salto do Rio",
        type: "Pesqueiro",
        lat: -23.1971, lng: -47.2934,
        rating: 4.4, reviewCount: 678,
        address: "Salto, SP",
        distance: "90 km da capital",
        state: "SP",
        species: ["Tilápia", "Pacu", "Tucunaré", "Tambaqui"],
        description: "Pesqueiro bem avaliado em Salto com lagos bem manejados e ótima estrutura de churrasco à beira d'água.",
        dicas: "Pacu e tambaqui no lago fundo. Use boliche de milho fermentado arremessado para as pedras.",
        regras: "Reserva recomendada para fins de semana.",
        preco: "R$ 75–110/dia",
        googleMapsUrl: "https://maps.google.com/?q=-23.1971,-47.2934"
    },
    {
        id: "represa_boa_esperanca",
        name: "Represa Boa Esperança — R. Paranaíba",
        type: "Represa",
        lat: -19.6312, lng: -45.5623,
        rating: 4.5, reviewCount: 1023,
        address: "Fronteira MG/GO — acessada via SP",
        distance: "560 km da capital",
        state: "SP",
        species: ["Dourado", "Tucunaré", "Pintado", "Piraputanga"],
        description: "Reservatório do Rio Paranaíba. Excelente para tucunaré e dourado. Menos conhecido mas de altíssima qualidade.",
        dicas: "Tucunaré na desembocadura de afluentes. Superfície no cedo com popper grande.",
        regras: "Licença IBAMA. Regulamentação MG/GO.",
        preco: "Pousadas R$ 150–300/diária.",
        googleMapsUrl: "https://maps.google.com/?q=-19.6312,-45.5623"
    },
    {
        id: "pesqueiro_jundiai_2",
        name: "Pesque-Pague Rancho da Serra",
        type: "Pesqueiro",
        lat: -23.1512, lng: -47.0023,
        rating: 4.3, reviewCount: 512,
        address: "Jundiaí, SP",
        distance: "58 km da capital",
        state: "SP",
        species: ["Tilápia", "Pacu", "Curimba", "Carpa", "Bagre"],
        description: "Opção de pesqueiro na Serra de Jundiaí com clima agradável e lago em ambiente serrano.",
        dicas: "Temperatura menor favorece curimba nas corredeiras do córrego que alimenta o lago.",
        regras: "Pesca apenas com varas. Proibido fogueira.",
        preco: "R$ 60–90/dia",
        googleMapsUrl: "https://maps.google.com/?q=-23.1512,-47.0023"
    },
];

async function seed() {
    console.log("🚀 Adicionando 40 novos spots ao Firestore (sem apagar os existentes)...\n");
    let count = 0;

    for (const spot of SPOTS_BATCH2) {
        const { id, ...data } = spot;
        data.dataAtualizacao = new Date().toISOString();
        await setDoc(doc(db, 'spots', id), data);
        console.log(`✅ ${spot.name} (${spot.type})`);
        count++;
    }

    console.log(`\n🎉 ${count} novos spots adicionados! Total agora: ${count + 36} spots.`);
    process.exit(0);
}

seed().catch(e => { console.error(e); process.exit(1); });
