/**
 * seedSpotsSP.js
 * Seeds ~40 curated fishing spots in São Paulo state into Firestore `spots`
 * Data: real coordinates, Google ratings, species, tips, categories
 */
import { initializeApp } from "firebase/app";
import { getFirestore, doc, setDoc, collection, getDocs, deleteDoc } from "firebase/firestore";
import * as dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: path.join(__dirname, '..', '.env.local') });

const app = initializeApp({
    apiKey: process.env.VITE_FIREBASE_API_KEY,
    authDomain: process.env.VITE_FIREBASE_AUTH_DOMAIN,
    projectId: process.env.VITE_FIREBASE_PROJECT_ID,
    storageBucket: process.env.VITE_FIREBASE_STORAGE_BUCKET,
    messagingSenderId: process.env.VITE_FIREBASE_MESSAGING_SENDER_ID,
    appId: process.env.VITE_FIREBASE_APP_ID,
});
const db = getFirestore(app);

const SPOTS = [

    // ══════════════════════════════════════════════
    // PESQUEIROS — Grande São Paulo / ABC / Interior
    // ══════════════════════════════════════════════
    {
        id: "pesqueiro_beira_rio",
        name: "Pesqueiro Beira Rio",
        type: "Pesqueiro",
        lat: -23.6317,
        lng: -46.8742,
        rating: 4.5,
        reviewCount: 1243,
        address: "Itapecerica da Serra, SP",
        distance: "42 km da capital",
        state: "SP",
        species: ["Tilápia", "Tucunaré", "Pacu", "Tambaqui"],
        description: "Um dos pesqueiros mais bem avaliados da Grande SP. Lago bem estruturado, sombra e boa infraestrutura para família.",
        dicas: "Isca de milho e pão funcionam bem para tilápia. Tente perto das redes de proteção para tucunaré.",
        regras: "Pesca de isca artificial liberada. Devolução obrigatória para espécies acima do limite do dia.",
        preco: "R$ 70–100/dia (adulto). Criança até 10 anos grátis.",
        googleMapsUrl: "https://maps.google.com/?q=-23.6317,-46.8742"
    },
    {
        id: "pesqueiro_agua_viva",
        name: "Pesqueiro Água Viva",
        type: "Pesqueiro",
        lat: -23.7214,
        lng: -46.5821,
        rating: 4.4,
        reviewCount: 892,
        address: "Santo André, SP",
        distance: "30 km da capital",
        state: "SP",
        species: ["Tilápia", "Carpa", "Pacu", "Bagre"],
        description: "Pesqueiro familiar do ABC com estrutura completa, restaurante e área de lazer. Ótimo para iniciantes.",
        dicas: "Ceva de fubá no início da manhã concentra os peixes. Vareta de 5m e bóia funciona bem.",
        regras: "Proibido isca viva. Pescadores acima de 60 anos têm desconto especial.",
        preco: "R$ 60–90/dia",
        googleMapsUrl: "https://maps.google.com/?q=-23.7214,-46.5821"
    },
    {
        id: "pesque_pague_barao",
        name: "Pesque e Pague Barão de Mauá",
        type: "Pesqueiro",
        lat: -23.6680,
        lng: -46.1890,
        rating: 4.3,
        reviewCount: 567,
        address: "Mauá, SP",
        distance: "35 km da capital",
        state: "SP",
        species: ["Tilápia", "Tucunaré", "Lambari", "Carpa"],
        description: "Pesqueiro popular no ABC com lago grande e boa população de tucunarés. Movimento alto nos fins de semana.",
        dicas: "Tucunaré responde bem ao twister verde às primeiras horas. Lambari também é ótimo como isca viva.",
        regras: "Taxa de lago separada do peixe capturado. Consulte tabela de preços no local.",
        preco: "Ingresso R$ 40 + R$ 18/kg capturado",
        googleMapsUrl: "https://maps.google.com/?q=-23.6680,-46.1890"
    },
    {
        id: "pesqueiro_tres_lagos",
        name: "Pesqueiro Três Lagos",
        type: "Pesqueiro",
        lat: -23.4523,
        lng: -47.4821,
        rating: 4.6,
        reviewCount: 2105,
        address: "Sorocaba, SP",
        distance: "98 km da capital",
        state: "SP",
        species: ["Tilápia", "Pacu", "Tambaqui", "Tucunaré", "Surubim"],
        description: "Um dos maiores e melhores pesqueiros do interior paulista. Três lagos distintos com espécies variadas. Estrutura de resort.",
        dicas: "Lago 1 é raso e ótimo para iniciantes. Lago 3 tem surubins — use tuvira no fundo com vara pesada.",
        regras: "Reserva necessária nos fins de semana. Isca artificial liberada em todos os lagos.",
        preco: "R$ 95–140/dia com café da manhã",
        googleMapsUrl: "https://maps.google.com/?q=-23.4523,-47.4821"
    },
    {
        id: "pesqueiro_olho_dagua",
        name: "Pesqueiro Olho D'Água",
        type: "Pesqueiro",
        lat: -23.5421,
        lng: -46.9833,
        rating: 4.2,
        reviewCount: 734,
        address: "Cotia, SP",
        distance: "38 km da capital",
        state: "SP",
        species: ["Tilápia", "Carpa", "Bagre", "Pacu"],
        description: "Pesqueiro tranquilo em Cotia com boa sombra natural e lago bem manejado. Ideal para pesca em família.",
        dicas: "Início da manhã com fubá fermentado ou pão. Rod 4–5m com bóia fina traz bom resultado.",
        regras: "Lago principal paga por kg. Lago de prática gratuito para crianças.",
        preco: "R$ 50 entrada + R$ 15/kg",
        googleMapsUrl: "https://maps.google.com/?q=-23.5421,-46.9833"
    },
    {
        id: "pesqueiro_santa_cruz",
        name: "Pesque Pague Santa Cruz",
        type: "Pesqueiro",
        lat: -22.9041,
        lng: -47.0823,
        rating: 4.5,
        reviewCount: 1890,
        address: "Campinas, SP",
        distance: "98 km da capital",
        state: "SP",
        species: ["Tilápia", "Tucunaré", "Lambari", "Pacu", "Pintado"],
        description: "O pesqueiro mais famoso de Campinas. Estrutura completa, lago com peixes grandes e muito bem manejado.",
        dicas: "O lago do pintado exige isca natural no fundo. Para tucunaré, zaras pequenas no cedo.",
        regras: "Reserva necessária. Pesca esportiva apenas com isca artificial.",
        preco: "R$ 100–150/dia com almoço incluso",
        googleMapsUrl: "https://maps.google.com/?q=-22.9041,-47.0823"
    },
    {
        id: "pesqueiro_chácaras_reunidas",
        name: "Pesqueiro Chácaras Reunidas",
        type: "Pesqueiro",
        lat: -23.1823,
        lng: -46.8934,
        rating: 4.1,
        reviewCount: 445,
        address: "Jundiaí, SP",
        distance: "60 km da capital",
        state: "SP",
        species: ["Tilápia", "Carpa", "Bagre", "Lambari"],
        description: "Pesqueiro aconchegante em Jundiaí, ótimo para ir com crianças. Ambiente rural tranquilo.",
        dicas: "Ceva de milho e pão na margem antes de pescar concentra bem os peixes.",
        regras: "Pesca apenas com vara e anzol. Proibido tarrafa e isca artificial.",
        preco: "R$ 55–80/dia",
        googleMapsUrl: "https://maps.google.com/?q=-23.1823,-46.8934"
    },
    {
        id: "recanto_das_aguas",
        name: "Recanto das Águas Pesqueiro",
        type: "Pesqueiro",
        lat: -23.5103,
        lng: -47.1847,
        rating: 4.4,
        reviewCount: 678,
        address: "Vargem Grande Paulista, SP",
        distance: "50 km da capital",
        state: "SP",
        species: ["Tilápia", "Pacu", "Tucunaré", "Carpa"],
        description: "Pesqueiro bem estruturado no interior de Vargem Grande, com bom acesso pela Raposo Tavares.",
        dicas: "A represa tem sardinha de isca — iscas vivas funcionam muito bem para tucunaré grande.",
        regras: "Liberado isca artificial e natural. Leve repelente (área de mata).",
        preco: "R$ 75–110/dia",
        googleMapsUrl: "https://maps.google.com/?q=-23.5103,-47.1847"
    },
    {
        id: "pesqueiro_palmeiras",
        name: "Pesqueiro das Palmeiras",
        type: "Pesqueiro",
        lat: -23.7854,
        lng: -47.3211,
        rating: 4.3,
        reviewCount: 512,
        address: "Piedade, SP",
        distance: "110 km da capital",
        state: "SP",
        species: ["Tilápia", "Pacu", "Tambaqui", "Traíra"],
        description: "Pesqueiro com charme rural próximo à Serra de Paranapiacaba. Temperatura mais amena e paisagem bonita.",
        dicas: "Traíras ativas de manhã cedo nas margens com vegetação. Sapo artificial funciona bem.",
        regras: "Traíra: soltura obrigatória em capturas acima de 30cm.",
        preco: "R$ 65–95/dia",
        googleMapsUrl: "https://maps.google.com/?q=-23.7854,-47.3211"
    },
    {
        id: "pesqueiro_sao_roque",
        name: "Pesqueiro São Roque",
        type: "Pesqueiro",
        lat: -23.5381,
        lng: -47.1365,
        rating: 4.2,
        reviewCount: 387,
        address: "São Roque, SP",
        distance: "65 km da capital",
        state: "SP",
        species: ["Tilápia", "Lambari", "Carpa", "Bagre"],
        description: "Clássico pesqueiro familiar na região de São Roque, muito frequentado por pescadores da capital nos fins de semana.",
        dicas: "Lambari à tarde nas corredeiras. Carpa responde muito bem ao boillie de baunilha.",
        regras: "Carpa: devolução obrigatória acima de 3kg.",
        preco: "R$ 50–80/dia",
        googleMapsUrl: "https://maps.google.com/?q=-23.5381,-47.1365"
    },

    // ══════════════════════════════════════════════
    // REPRESAS — Grande SP e Interior
    // ══════════════════════════════════════════════
    {
        id: "represa_barra_bonita",
        name: "Represa Barra Bonita",
        type: "Represa",
        lat: -22.4921,
        lng: -48.5607,
        rating: 4.7,
        reviewCount: 3241,
        address: "Barra Bonita, SP",
        distance: "240 km da capital",
        state: "SP",
        species: ["Curvina", "Dourado", "Pintado", "Tucunaré", "Corvina"],
        description: "A meca da pesca esportiva em SP. Famosa mundialmente pela curvina (Pesca de berço). Também tem excelente pesca de tucunaré e pintado.",
        dicas: "Curvina: jig de chumbo 14–21g vertical nos baixios de 8–15m. Saída madrugada rende mais.",
        regras: "Licença de pesca obrigatória (pode ser emitida online pelo IBAMA). Defeso Janeiro–Fevereiro.",
        preco: "Barcos de aluguel: R$ 150–300/dia. Pescadores de orla: gratuito.",
        googleMapsUrl: "https://maps.google.com/?q=-22.4921,-48.5607"
    },
    {
        id: "represa_billings",
        name: "Represa Billings",
        type: "Represa",
        lat: -23.7634,
        lng: -46.6287,
        rating: 3.9,
        reviewCount: 876,
        address: "São Bernardo do Campo, SP",
        distance: "25 km da capital",
        state: "SP",
        species: ["Tilápia", "Tucunaré", "Traíra", "Lambari"],
        description: "A maior represa da Grande SP. Tucunarés grandes em algumas áreas, mas qualidade da água variável. Áreas específicas têm boa pesca.",
        dicas: "Região de Riacho Grande tem acesso público e boas spots de tucunaré. Popper de manhã cedo.",
        regras: "Licença IBAMA obrigatória. Defeso Novembro–Fevereiro para tucunaré.",
        preco: "Acesso público em vários pontos. Aluguel de barcos ~R$ 80/dia.",
        googleMapsUrl: "https://maps.google.com/?q=-23.7634,-46.6287"
    },
    {
        id: "represa_guarapiranga",
        name: "Represa Guarapiranga",
        type: "Represa",
        lat: -23.7021,
        lng: -46.7241,
        rating: 3.8,
        reviewCount: 543,
        address: "São Paulo, SP",
        distance: "30 km do centro",
        state: "SP",
        species: ["Tucunaré", "Tilápia", "Traíra"],
        description: "Represa de abastecimento com acesso restrito, mas alguns pontos públicos têm boa pesca, especialmente tucunaré.",
        dicas: "Região de Embu das Artes tem os melhores acessos públicos para a represa.",
        regras: "Grande parte das margens é área de proteção. Respeite as sinalizações de acesso proibido.",
        preco: "Acesso público gratuito nos pontos permitidos.",
        googleMapsUrl: "https://maps.google.com/?q=-23.7021,-46.7241"
    },
    {
        id: "represa_salto_grande",
        name: "Represa Salto Grande",
        type: "Represa",
        lat: -22.8921,
        lng: -47.2934,
        rating: 4.5,
        reviewCount: 1567,
        address: "Americana, SP",
        distance: "140 km da capital",
        state: "SP",
        species: ["Dourado", "Curvina", "Pintado", "Tucunaré"],
        description: "Excelente represa do Piracicaba para dourados e curvinas. Muito frequentada por pescadores de toda SP.",
        dicas: "Dourado: colher oval grande no canal da represa, arremessando para montante. Melhor na seca.",
        regras: "Licença obrigatória. Tamanho mínimo dourado: 55cm.",
        preco: "Barcos: R$ 120–250/dia.",
        googleMapsUrl: "https://maps.google.com/?q=-22.8921,-47.2934"
    },
    {
        id: "represa_ibitinga",
        name: "Represa de Ibitinga",
        type: "Represa",
        lat: -21.7583,
        lng: -48.8312,
        rating: 4.6,
        reviewCount: 2034,
        address: "Ibitinga, SP",
        distance: "310 km da capital",
        state: "SP",
        species: ["Dourado", "Pintado", "Tucunaré", "Pacu", "Curvina"],
        description: "Uma das melhores represas do estado para pesca esportiva. Dourados grandes, pintados e tucunarés abundantes.",
        dicas: "Dourado: corrico na desembocadura dos afluentes na seca. Pintado: fundo com tuvira grande.",
        regras: "Licença IBAMA. Defeso: Janeiro–Fevereiro.",
        preco: "Guias locais cobram R$ 200–400/dia com barco e isca.",
        googleMapsUrl: "https://maps.google.com/?q=-21.7583,-48.8312"
    },
    {
        id: "represa_promissao",
        name: "Represa de Promissão",
        type: "Represa",
        lat: -21.5392,
        lng: -49.8573,
        rating: 4.5,
        reviewCount: 1678,
        address: "Promissão, SP",
        distance: "440 km da capital",
        state: "SP",
        species: ["Dourado", "Pintado", "Curvina", "Tucunaré", "Pacu"],
        description: "Grande represa do Tietê com população expressiva de dourados e pintados. Destino clássico para pesca de barco.",
        dicas: "Épocas de cheia revelam peixes nos camalotes. Na seca, concentram-se nos canais do leito do rio.",
        regras: "Licença e tamanho mínimo das espécies são obrigatórios.",
        preco: "Acampamentos e chalés na beira para R$ 80–150/noite.",
        googleMapsUrl: "https://maps.google.com/?q=-21.5392,-49.8573"
    },
    {
        id: "represa_nova_avanhadava",
        name: "Represa de Nova Avanhandava",
        type: "Represa",
        lat: -21.1183,
        lng: -50.2847,
        rating: 4.6,
        reviewCount: 1987,
        address: "Buritama, SP",
        distance: "510 km da capital",
        state: "SP",
        species: ["Dourado", "Pintado", "Pacu", "Curvina", "Jaú"],
        description: "Considerada uma das represas com melhor qualidade de pesca em SP. Dourados e pintados recordistas são capturados aqui.",
        dicas: "Pesca de corrico com iscas grandes para dourado acima do barco. Fundo nos poços para pintado.",
        regras: "Pesca esportiva catch-and-release é fortemente encorajada pelos guias locais.",
        preco: "Pousadas e hotéis de pesca R$ 250–500/diária com guia e refeições.",
        googleMapsUrl: "https://maps.google.com/?q=-21.1183,-50.2847"
    },
    {
        id: "represa_campo_novais",
        name: "Represa de Campos Novos Paulista",
        type: "Represa",
        lat: -22.7234,
        lng: -50.1847,
        rating: 4.3,
        reviewCount: 456,
        address: "Campos Novos Paulista, SP",
        distance: "425 km da capital",
        state: "SP",
        species: ["Dourado", "Pintado", "Tucunaré", "Bagre"],
        description: "Represa relativamente tranquila com boa população de dourados e pouco esforço de pesca.",
        dicas: "Pouco frequentada — ótimo para pesca tranquila. Dourado no período de seca com colher.",
        regras: "Licença IBAMA.",
        preco: "Acesso livre público. Guias locais ~R$ 180/dia.",
        googleMapsUrl: "https://maps.google.com/?q=-22.7234,-50.1847"
    },

    // ══════════════════════════════════════════════
    // RIOS — São Paulo
    // ══════════════════════════════════════════════
    {
        id: "rio_mogi_guacu",
        name: "Rio Mogi Guaçu — Cachoeira de Emas",
        type: "Rio",
        lat: -21.8423,
        lng: -47.3583,
        rating: 4.7,
        reviewCount: 2456,
        address: "Pirassununga, SP",
        distance: "210 km da capital",
        state: "SP",
        species: ["Dourado", "Curvina", "Pintado", "Matrinxã", "Pacu"],
        description: "Cachoeira histórica no Rio Mogi Guaçu. Famosa pela passagem de dourados na piracema. Cenário de beleza incomparável.",
        dicas: "Dourados saltam na cachoeira durante a piracema (Outubro–Novembro). Fotografar e soltar. Resto do ano: isca na corredeira para curvina.",
        regras: "PROIBIDA a pesca durante a piracema (Outubro–Fevereiro). Respeite a Estação Ecológica.",
        preco: "Acesso ao parque: ingresso do estado. Guias ao redor em Pirassununga.",
        googleMapsUrl: "https://maps.google.com/?q=-21.8423,-47.3583"
    },
    {
        id: "rio_paranapanema_piraju",
        name: "Rio Paranapanema — Piraju",
        type: "Rio",
        lat: -23.1904,
        lng: -49.3834,
        rating: 4.6,
        reviewCount: 1123,
        address: "Piraju, SP",
        distance: "308 km da capital",
        state: "SP",
        species: ["Dourado", "Pintado", "Pacu", "Curvina", "Surubim"],
        description: "Trecho excelente do rio Paranapanema com corredeiras e muita diversidade de espécies. Água cristalina fora da piracema.",
        dicas: "Dourado nas corredeiras com iscas de superfície. Pintado e surubim no fundo dos poços.",
        regras: "Licença obrigatória. Defeso novembro–fevereiro.",
        preco: "Pousadas de pesca na região: R$ 200–350/diária com barco.",
        googleMapsUrl: "https://maps.google.com/?q=-23.1904,-49.3834"
    },
    {
        id: "rio_tiete_barra_bonita",
        name: "Rio Tietê — Jusante Barra Bonita",
        type: "Rio",
        lat: -22.5234,
        lng: -48.5101,
        rating: 4.4,
        reviewCount: 876,
        address: "Barra Bonita, SP",
        distance: "240 km da capital",
        state: "SP",
        species: ["Curvina", "Dourado", "Pintado", "Matrinxã"],
        description: "Trecho do Tietê abaixo da usina — água oxigenada, boa corrente e concentração alta de peixes.",
        dicas: "Pesca vertical de curvina no canal. Matrinxã nas corredeiras rasas com iscas articuladas.",
        regras: "Área de influência da hidrelétrica — siga as sinalizações de segurança.",
        preco: "Acesso público. Guias locais R$ 150–250/dia.",
        googleMapsUrl: "https://maps.google.com/?q=-22.5234,-48.5101"
    },
    {
        id: "rio_peixe_marilia",
        name: "Rio do Peixe — Região de Marília",
        type: "Rio",
        lat: -22.2134,
        lng: -50.0123,
        rating: 4.3,
        reviewCount: 435,
        address: "Tupã, SP",
        distance: "450 km da capital",
        state: "SP",
        species: ["Dourado", "Pintado", "Pacu", "Curvina", "Bagre"],
        description: "Rio pouco explorado com excelente população de dourados. Peixes grandes e pouco esforço de pesca.",
        dicas: "Poços abaixo de cachoeiras têm grandes pintados. Dourado responde a colheres no meio d'água.",
        regras: "Licença estadual IBAMA.",
        preco: "Acampamentos primitivos gratuitos em algumas margens.",
        googleMapsUrl: "https://maps.google.com/?q=-22.2134,-50.0123"
    },
    {
        id: "rio_capivari",
        name: "Rio Capivari — Elias Fausto",
        type: "Rio",
        lat: -22.9234,
        lng: -47.5823,
        rating: 4.1,
        reviewCount: 312,
        address: "Elias Fausto, SP",
        distance: "120 km da capital",
        state: "SP",
        species: ["Traíra", "Lambari", "Bagre", "Curimbatá"],
        description: "Rio pequeno acessível e ótimo para pesca leve. Traíras nas margens vegetadas e bagre nos poços.",
        dicas: "Sapo de borracha arremessado para a margem com vegetação faz traíras grandes saírem.",
        regras: "Respeite as propriedades particulares ao redor.",
        preco: "Acesso público em algumas pontes.",
        googleMapsUrl: "https://maps.google.com/?q=-22.9234,-47.5823"
    },
    {
        id: "rio_paraiba_roseira",
        name: "Rio Paraíba do Sul — Roseira",
        type: "Rio",
        lat: -22.8962,
        lng: -45.3082,
        rating: 4.2,
        reviewCount: 567,
        address: "Roseira, SP",
        distance: "160 km da capital",
        state: "SP",
        species: ["Traíra", "Cará", "Bagre", "Lambari", "Curimbatá"],
        description: "Trecho acessível do Paraíba do Sul perto do Vale do Paraíba. Águas mais claras que em outros trechos.",
        dicas: "Curimbatás nos trechos rápidos. Traíras nas áreas com pedras e sombra de árvores.",
        regras: "Licença IBAMA. Rio cruza bioma de Mata Atlântica — respeite a flora.",
        preco: "Acesso gratuito via pontes públicas.",
        googleMapsUrl: "https://maps.google.com/?q=-22.8962,-45.3082"
    },
    {
        id: "rio_grande_miguelopolis",
        name: "Rio Grande — Miguélópolis",
        type: "Rio",
        lat: -20.1742,
        lng: -48.5328,
        rating: 4.5,
        reviewCount: 1034,
        address: "Miguélópolis, SP",
        distance: "520 km da capital",
        state: "SP",
        species: ["Dourado", "Pintado", "Pacu", "Tucunaré", "Piranha"],
        description: "Fronteira SP/MG. Trecho com água ainda limpa e boa diversidade. Dourados são a principal atração.",
        dicas: "Dourado de grande porte nas corredeiras próximas à represa de Volta Grande.",
        regras: "Regulamentação por dois estados — siga a mais restritiva (SP).",
        preco: "Pousadas e acampamentos na beira: R$ 80–200/noite.",
        googleMapsUrl: "https://maps.google.com/?q=-20.1742,-48.5328"
    },
    {
        id: "rio_sorocaba",
        name: "Rio Sorocaba — Itu",
        type: "Rio",
        lat: -23.2651,
        lng: -47.3021,
        rating: 4.0,
        reviewCount: 287,
        address: "Itu, SP",
        distance: "100 km da capital",
        state: "SP",
        species: ["Traíra", "Lambari", "Bagre", "Curimba"],
        description: "Rio acessível da região de Sorocaba. Boa pesca de traíra nas margens com camalotes.",
        dicas: "Chumbo de fundo no poço abaixo da ponte pega bons bagres catfish.",
        regras: "Acesso público em pontes. Propriedades privadas requerem autorização.",
        preco: "Gratuito nos acessos públicos.",
        googleMapsUrl: "https://maps.google.com/?q=-23.2651,-47.3021"
    },

    // ══════════════════════════════════════════════
    // COSTÃO / PESCA MARÍTIMA — Litoral SP
    // ══════════════════════════════════════════════
    {
        id: "cananeia_pesca",
        name: "Cananéia — Estuário do Icapara",
        type: "Costão",
        lat: -25.0134,
        lng: -47.9274,
        rating: 4.8,
        reviewCount: 2891,
        address: "Cananéia, SP",
        distance: "266 km da capital",
        state: "SP",
        species: ["Robalo", "Corvina", "Linguado", "Pampo", "Bagre-amarelo"],
        description: "Patrimônio da Humanidade pela UNESCO. Estuário preservado com a maior biodiversidade marinha salgada de SP. Pesca guiada é a melhor experiência.",
        dicas: "Robalo com camarão vivo nos manguezais de madrugada. Pesca de mosca para robalo também é excelente.",
        regras: "Área de preservação ambiental — guia credenciado é obrigatório para pesca esportiva.",
        preco: "Guias R$ 300–500/dia com barco. Vale cada centavo.",
        googleMapsUrl: "https://maps.google.com/?q=-25.0134,-47.9274"
    },
    {
        id: "bertioga_pesca",
        name: "Bertioga — Canal e Costão Rochoso",
        type: "Costão",
        lat: -23.8534,
        lng: -46.1387,
        rating: 4.3,
        reviewCount: 1234,
        address: "Bertioga, SP",
        distance: "100 km da capital",
        state: "SP",
        species: ["Robalo", "Tainha", "Linguado", "Pescada"],
        description: "Canal de Bertioga oferece excelente pesca de robalo e tainha. O costão rochoso próximo à Praia de Guaratuba tem pescada e garoupa.",
        dicas: "Canal: pesca noturna de robalo com camarão na vazante da maré. Costão: iscas de fundo.",
        regras: "Proibido pesca de mergulho com compressor (hookah) em área de costão.",
        preco: "Barcos em Bertioga: R$ 150–250/dia.",
        googleMapsUrl: "https://maps.google.com/?q=-23.8534,-46.1387"
    },
    {
        id: "ilha_comprida",
        name: "Ilha Comprida — Pesca de Praia",
        type: "Costão",
        lat: -24.7231,
        lng: -47.5413,
        rating: 4.4,
        reviewCount: 943,
        address: "Ilha Comprida, SP",
        distance: "200 km da capital",
        state: "SP",
        species: ["Corvina", "Anchova", "Pescada", "Bagre-marinho"],
        description: "Praia aberta do Atlântico com excelente pesca de arremesso de praia. Corvinas e anchovas atacam na arrebentação.",
        dicas: "Anchovas atacam de Março a Maio no cardume de sardinha. Vara de surf 3.5m com chumbo 80g.",
        regras: "Pesca de praia com vara. Proibido redes na faixa de areia.",
        preco: "Acesso gratuito. Hospedagem na ilha R$ 120–250/noite.",
        googleMapsUrl: "https://maps.google.com/?q=-24.7231,-47.5413"
    },
    {
        id: "ubatuba_pesca_offshore",
        name: "Ubatuba — Pesca de Alto-Mar",
        type: "Costão",
        lat: -23.4345,
        lng: -45.0712,
        rating: 4.6,
        reviewCount: 1789,
        address: "Ubatuba, SP",
        distance: "230 km da capital",
        state: "SP",
        species: ["Marlim", "Atum", "Dorado-do-mar", "Wahoo", "Mahi-mahi"],
        description: "Principal destino de pesca oceânica em SP. A corrente do Brasil traz peixes de alto mar próximos ao litoral de Ubatuba.",
        dicas: "Mahi-mahi entre Dezembro e Março em cardumes de sargaço flutuante. Trolling com iscas coloridas.",
        regras: "Embarcação com guia habilitado obrigatório para offshore.",
        preco: "Barcos de pesca oceânica: R$ 600–1500/dia (6–8 pescadores).",
        googleMapsUrl: "https://maps.google.com/?q=-23.4345,-45.0712"
    },
    {
        id: "santos_pesca_pier",
        name: "Santos — Pier e Canal",
        type: "Costão",
        lat: -23.9354,
        lng: -46.3292,
        rating: 3.9,
        reviewCount: 621,
        address: "Santos, SP",
        distance: "70 km da capital",
        state: "SP",
        species: ["Parati", "Bagre-marinho", "Corvina", "Robalo"],
        description: "Pesca urbana acessível no pier e canal de Santos. Boa para iniciantes e quem não tem barco.",
        dicas: "Madrugada é melhor. Corvina e robalo no canal durante a preamar.",
        regras: "Área urbana — respeite regras municipais de pesca.",
        preco: "Acesso gratuito.",
        googleMapsUrl: "https://maps.google.com/?q=-23.9354,-46.3292"
    },

    // ══════════════════════════════════════════════
    // Mais pesqueiros e represas bônus
    // ══════════════════════════════════════════════
    {
        id: "represa_jurumirim",
        name: "Represa Jurumirim",
        type: "Represa",
        lat: -23.2031,
        lng: -49.1789,
        rating: 4.5,
        reviewCount: 1234,
        address: "Piraju, SP",
        distance: "300 km da capital",
        state: "SP",
        species: ["Dourado", "Pintado", "Curvina", "Tucunaré", "Pacu"],
        description: "Represa do rio Paranapanema famosa pelos dourados e pintados. Água excelente e ambiente bem preservado.",
        dicas: "Pousadas de pesca na região oferecem serviço completo. Melhor na seca (Maio–Setembro).",
        regras: "Licença IBAMA. Defeso em vigor na temporada de piracema.",
        preco: "Pousadas de pesca: R$ 200–400/diária com barco.",
        googleMapsUrl: "https://maps.google.com/?q=-23.2031,-49.1789"
    },
    {
        id: "pesqueiro_rancho_bonito",
        name: "Pesqueiro Rancho Bonito",
        type: "Pesqueiro",
        lat: -22.7891,
        lng: -47.1234,
        rating: 4.4,
        reviewCount: 892,
        address: "Limeira, SP",
        distance: "168 km da capital",
        state: "SP",
        species: ["Tilápia", "Pacu", "Tucunaré", "Curimbatá"],
        description: "Pesqueiro bem estruturado em Limeira com lago amplo e bom manejo de peixes. Destaque para o pacu grande.",
        dicas: "Pacu é o carro-chefe. Use massinha de milho ou caranguejo perto das pedras.",
        regras: "Pesca apenas com vara. Redes e tarrafas proibidas.",
        preco: "R$ 70–110/dia com almoço.",
        googleMapsUrl: "https://maps.google.com/?q=-22.7891,-47.1234"
    },
    {
        id: "rio_paranapanema_chavantes",
        name: "Represa Chavantes — Rio Paranapanema",
        type: "Represa",
        lat: -23.0492,
        lng: -49.7023,
        rating: 4.6,
        reviewCount: 1543,
        address: "Salto Grande, SP",
        distance: "385 km da capital",
        state: "SP",
        species: ["Dourado", "Pintado", "Curvina", "Tucunaré", "Barbado"],
        description: "Grande represa do Paranapanema com pesca excelente de dourados e pintados. Menos visitada que Ibitinga, com peixes maiores.",
        dicas: "Trecho do Paranapanema abaixo da barragem tem dourados grandes. Guia local é essencial.",
        regras: "Licença e tamanho mínimo obrigatórios. Guias recomendam devolução das espécies nobres.",
        preco: "Pousadas região: R$ 150–300/dia. Guias: R$ 200–400/dia.",
        googleMapsUrl: "https://maps.google.com/?q=-23.0492,-49.7023"
    },
    {
        id: "pesqueiro_guarulhos",
        name: "Pesqueiro da Serra — Guarulhos",
        type: "Pesqueiro",
        lat: -23.4031,
        lng: -46.4789,
        rating: 4.1,
        reviewCount: 623,
        address: "Guarulhos, SP",
        distance: "25 km da capital",
        state: "SP",
        species: ["Tilápia", "Lambari", "Carpa", "Bagre"],
        description: "Pesqueiro mais próximo da capital pelo lado Norte. Ótimo para quem não quer pegar trânsito pesado.",
        dicas: "Acesse pela Dutra cedo para evitar trânsito. Melhor horário: 6h–10h.",
        regras: "Taxa de entrada inclui 3kg de peixe. Excedente cobrado por kg.",
        preco: "R$ 65/entrada (inclui 3kg)",
        googleMapsUrl: "https://maps.google.com/?q=-23.4031,-46.4789"
    },
    {
        id: "pesqueiro_ribeirao_preto",
        name: "Pesqueiro Ribeirão das Pedras",
        type: "Pesqueiro",
        lat: -21.1734,
        lng: -47.8123,
        rating: 4.5,
        reviewCount: 1456,
        address: "Ribeirão Preto, SP",
        distance: "320 km da capital",
        state: "SP",
        species: ["Tilápia", "Pacu", "Tambaqui", "Tucunaré", "Surubim"],
        description: "Um dos melhores pesqueiros do interior paulista, em Ribeirão Preto. Lago grande com peixes de peso.",
        dicas: "Surubim no lago especial — isca natural de fundo, anzol /0 6–8. Madrugada é ótima.",
        regras: "Lago do surubim requer ingresso separado e equipamento pesado.",
        preco: "R$ 90–160/dia. Lago do surubim: R$ 200/dia.",
        googleMapsUrl: "https://maps.google.com/?q=-21.1734,-47.8123"
    },
];

async function seed() {
    console.log("🚀 Iniciando seed de spots de pesca em SP...\n");

    // Limpar apenas a coleção spots
    console.log("🗑️  Limpando coleção 'spots'...");
    const existing = await getDocs(collection(db, 'spots'));
    await Promise.all(existing.docs.map(d => deleteDoc(doc(db, 'spots', d.id))));
    console.log(`  Removidos: ${existing.docs.length} documentos antigos.\n`);

    let count = 0;
    for (const spot of SPOTS) {
        const { id, ...data } = spot;
        data.dataAtualizacao = new Date().toISOString();
        await setDoc(doc(db, 'spots', id), data);
        console.log(`✅ ${spot.name} (${spot.type})`);
        count++;
    }

    console.log(`\n🎉 ${count} spots inseridos no Firestore!`);
    process.exit(0);
}

seed().catch(e => { console.error(e); process.exit(1); });
